2021-09-26 11:44:53,830 ERROR: Exception on / [GET] [in c:\users\anton\downloads\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\anton\downloads\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\anton\downloads\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\anton\downloads\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\anton\downloads\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\anton\downloads\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\routes.py", line 53, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "c:\users\anton\downloads\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "c:\users\anton\downloads\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\anton\downloads\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\users\anton\downloads\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\anton\downloads\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\anton\downloads\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "c:\users\anton\downloads\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "c:\users\anton\downloads\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\templates\base.html", line 28, in block 'navbar'
    <li><a href="{{ url_for('messages') }}">
  File "c:\users\anton\downloads\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\anton\downloads\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "c:\users\anton\downloads\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'messages'. Did you mean 'send_message' instead?
2021-09-26 11:49:15,914 INFO: Howler startup [in C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\__init__.py:60]
2021-09-26 11:52:31,390 INFO: Howler startup [in C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\__init__.py:60]
2021-09-26 11:58:12,735 INFO: Howler startup [in C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\__init__.py:60]
2021-09-26 11:58:14,108 ERROR: Exception on / [GET] [in c:\users\anton\downloads\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\anton\downloads\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\anton\downloads\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\anton\downloads\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\anton\downloads\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\anton\downloads\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\routes.py", line 53, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "c:\users\anton\downloads\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "c:\users\anton\downloads\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\anton\downloads\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\users\anton\downloads\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\anton\downloads\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\anton\downloads\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "c:\users\anton\downloads\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "c:\users\anton\downloads\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block scripts %}
  File "C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\templates\base.html", line 125, in block 'scripts'
    $.ajax('{{ url_for('main.notifications') }}?since=' + since).done(
  File "c:\users\anton\downloads\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\anton\downloads\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "c:\users\anton\downloads\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.notifications'. Did you mean 'notifications' instead?
2021-09-26 11:59:21,785 INFO: Howler startup [in C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\__init__.py:60]
2021-09-26 12:30:34,380 INFO: Howler startup [in C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\__init__.py:60]
2021-09-26 12:34:24,760 INFO: Howler startup [in C:\Users\anton\Downloads\Dissertation Folder\NewHowler-5afd7201a232c3e73e2854027d7564bcaaef174f\app\__init__.py:60]
